name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  build_and_test:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: CI -- check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: CI -- fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: CI -- test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args:  --locked
          
      - name: CI -- lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps
      
      - name: func test
        run: |
          echo "@a\nAAA\n+\nAAA\n@c\nCCC\n+\nCCC\n@t\nTTT\n+\nTTT" | gzip > test.fq.gz && \
          echo "a\nt" > id_list && \
          echo "@a\nAAA\n+AAA\n@t\nTTT\n+\nTTT" > expected.fq && \
          cargo run -- --in-fastq test.fq.gz --in-id-list id_list > out.fq && \
          diff expected.fq out.fq > /dev/null; echo "exit code: $?"

